"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Bout={id:string;eventId:string;boxerA:string;boxerB:string;rounds:number|null;weight:string;status:string};
type EventItem={id:string;name:string;date:string;venue:string;promoter:string;status:string;bouts:Bout[]};
const statusLabels:Record<string,string>={planning:"準備中",matching:"マッチメイク中",confirmed:"カード確定",completed:"終了",cancelled:"中止"};
const demo:EventItem[]=[{id:"demo-1",name:"RING NIGHT 27",date:"2026-11-20",venue:"後楽園ホール",promoter:"東京プロモーション",status:"matching",bouts:[{id:"b1",eventId:"demo-1",boxerA:"山田 直樹",boxerB:"対戦相手募集中",rounds:6,weight:"55.0kg",status:"募集中"},{id:"b2",eventId:"demo-1",boxerA:"佐藤 海斗",boxerB:"田中 健",rounds:6,weight:"55.0kg",status:"決定"}]}];

export function EventBoard({databaseConnected,industryMode}:{databaseConnected:boolean;industryMode:boolean}){
  const [events,setEvents]=useState<EventItem[]>(databaseConnected?[]:demo); const [loading,setLoading]=useState(databaseConnected); const [error,setError]=useState(""); const [showForm,setShowForm]=useState(false);
  const [name,setName]=useState(""); const [date,setDate]=useState(""); const [venue,setVenue]=useState("");

  useEffect(()=>{if(!databaseConnected){return;}if(!industryMode){setLoading(false);return;}let active=true;(async()=>{try{const supabase=createClient();const {data:eventRows,error:eventError}=await supabase.schema("ringops").from("events").select("id,promoter_organization_id,name,event_date,venue_name,status").order("event_date");if(eventError)throw eventError;const eventIds=(eventRows??[]).map((e:any)=>e.id);const orgIds=[...new Set((eventRows??[]).map((e:any)=>e.promoter_organization_id))];const [{data:orgs},{data:boutRows}]=await Promise.all([orgIds.length?supabase.schema("ringops").from("organizations").select("id,display_name").in("id",orgIds):Promise.resolve({data:[]}),eventIds.length?supabase.schema("ringops").from("bouts").select("id,event_id,boxer_a_id,boxer_b_id,contract_weight_kg,scheduled_rounds,winner_boxer_id").in("event_id",eventIds):Promise.resolve({data:[]})]);const boxerIds=[...new Set((boutRows??[]).flatMap((b:any)=>[b.boxer_a_id,b.boxer_b_id]).filter(Boolean))];const {data:boxers}=boxerIds.length?await supabase.schema("ringops").from("boxers").select("id,name").in("id",boxerIds):{data:[]};const orgMap=new Map((orgs??[]).map((o:any)=>[o.id,o.display_name]));const boxerMap=new Map((boxers??[]).map((b:any)=>[b.id,b.name]));const mapped=(eventRows??[]).map((e:any)=>({id:e.id,name:e.name,date:e.event_date,venue:e.venue_name,promoter:orgMap.get(e.promoter_organization_id)??"興行主",status:e.status,bouts:(boutRows??[]).filter((b:any)=>b.event_id===e.id).map((b:any)=>({id:b.id,eventId:e.id,boxerA:boxerMap.get(b.boxer_a_id)??"空き枠",boxerB:boxerMap.get(b.boxer_b_id)??"対戦相手未定",rounds:b.scheduled_rounds,weight:b.contract_weight_kg!=null?`${b.contract_weight_kg}kg`:"—",status:b.boxer_a_id&&b.boxer_b_id?"決定":"募集中"}))}));if(active)setEvents(mapped);}catch{if(active)setError("興行情報を読み込めませんでした。") }finally{if(active)setLoading(false)}})();return()=>{active=false}},[databaseConnected,industryMode]);

  async function createEvent(e:React.FormEvent){e.preventDefault();setError("");if(!databaseConnected){setEvents([{id:`demo-${Date.now()}`,name,date,venue,promoter:"自組織",status:"planning",bouts:[]},...events]);setShowForm(false);return;}try{const supabase=createClient();const {data:userData}=await supabase.auth.getUser();if(!userData.user)throw new Error();const {data:memberships}=await supabase.schema("ringops").from("organization_memberships").select("organization_id,role").eq("user_id",userData.user.id).eq("status","active").in("role",["owner","admin","matchmaker"]);const ids=(memberships??[]).map((m:any)=>m.organization_id);const {data:orgs}=ids.length?await supabase.schema("ringops").from("organizations").select("id,organization_type").in("id",ids):{data:[]};const promoter=(orgs??[]).find((o:any)=>o.organization_type==="promoter");if(!promoter)throw new Error();const {error:insertError}=await supabase.schema("ringops").from("events").insert({promoter_organization_id:promoter.id,name,event_date:date,venue_name:venue,status:"planning",created_by:userData.user.id});if(insertError)throw insertError;location.reload();}catch{setError("興行を作成できませんでした。興行主組織の権限を確認してください。");}}

  if(loading)return <div className="border-y-2 border-slate-950 bg-white py-12 text-center text-sm font-bold text-slate-500">興行を読み込んでいます…</div>;
  return <>
    <div className="mb-4 flex items-center justify-between"><p className="text-xs font-bold text-slate-500">興行 {events.length}件</p>{industryMode&&<button className="h-10 bg-slate-950 px-4 text-xs font-black text-white" onClick={()=>setShowForm(!showForm)}>{showForm?"閉じる":"興行を作成"}</button>}</div>
    {error&&<div className="mb-4 border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-800">{error}</div>}
    {showForm&&<form className="mb-6 grid gap-3 border-y-2 border-slate-950 bg-white p-5 sm:grid-cols-[1fr_180px_1fr_auto] sm:items-end" onSubmit={createEvent}><Field label="興行名"><input className="input" required value={name} onChange={e=>setName(e.target.value)} /></Field><Field label="興行日"><input className="input" type="date" required value={date} onChange={e=>setDate(e.target.value)} /></Field><Field label="会場"><input className="input" required value={venue} onChange={e=>setVenue(e.target.value)} /></Field><button className="h-11 bg-slate-950 px-5 text-xs font-black text-white">作成</button></form>}
    <div className="divide-y divide-slate-200 border-y-2 border-slate-950 bg-white">{events.map(event=><article className="grid gap-5 px-5 py-6 lg:grid-cols-[260px_1fr]" key={event.id}><div><div className="flex items-center gap-2"><h2 className="text-lg font-black">{event.name}</h2><span className="border border-slate-200 bg-slate-50 px-2 py-1 text-[10px] font-black text-slate-600">{statusLabels[event.status]??event.status}</span></div><p className="mt-3 text-sm font-black">{event.date}</p><p className="mt-1 text-xs text-slate-500">{event.venue}</p><p className="mt-1 text-xs text-slate-500">{event.promoter}</p></div><div><div className="flex items-center justify-between border-b border-slate-900 pb-2"><p className="text-[11px] font-black text-slate-400">対戦カード</p><p className="text-[11px] font-bold text-slate-500">{event.bouts.length}試合</p></div>{event.bouts.map(b=><div className="grid gap-2 border-b border-slate-200 py-3 text-sm sm:grid-cols-[1fr_120px_100px]" key={b.id}><div><b>{b.boxerA} vs {b.boxerB}</b><p className="mt-1 text-xs text-slate-500">{b.weight} / {b.rounds?`${b.rounds}R`:"R未定"}</p></div><span className="text-xs font-black">{b.status}</span>{b.status==="募集中"&&<a className="text-xs font-black underline underline-offset-4" href="/open-matches">対戦相手募集へ</a>}</div>)}{!event.bouts.length&&<div className="py-6 text-sm font-bold text-slate-500">対戦カードはまだ登録されていません。</div>}</div></article>)}{!events.length&&<div className="py-12 text-center text-sm font-bold text-slate-500">興行がありません。</div>}</div>
  </>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-[11px] font-black text-slate-500">{label}</span>{children}</label>}
