"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { divisions } from "@/features/boxers/data/preview-boxers";

type Item={id:string;targetBoxer:string;organization:string;date:string;venue:string;division:string;weight:string;rounds:number;klass:string;stance:string;deadline:string;note:string};
const divisionCodes:Record<string,string>={"ミニマム級":"minimum","ライトフライ級":"light_fly","フライ級":"fly","スーパーフライ級":"super_fly","バンタム級":"bantam","スーパーバンタム級":"super_bantam","フェザー級":"feather","スーパーフェザー級":"super_feather","ライト級":"light","スーパーライト級":"super_light","ウェルター級":"welter","スーパーウェルター級":"super_welter","ミドル級":"middle","スーパーミドル級":"super_middle","ライトヘビー級":"light_heavy","クルーザー級":"cruiser","ヘビー級":"heavy"};
const codeToDivision=Object.fromEntries(Object.entries(divisionCodes).map(([label,code])=>[code,label]));
const stanceToDb:Record<string,string|undefined>={"指定なし":undefined,"右":"orthodox","左":"southpaw"};
const classToDb:Record<string,string|undefined>={"指定なし":undefined,"A級":"A","B級":"B","C級":"C"};
const demo:Item[]=[{id:"demo-1",targetBoxer:"山田 直樹",organization:"青空ボクシングジム",date:"2026-11-20",venue:"後楽園ホール",division:"スーパーバンタム級",weight:"55.0kg",rounds:6,klass:"B級",stance:"指定なし",deadline:"2026-09-30",note:"戦績5〜10戦程度を希望。"},{id:"demo-2",targetBoxer:"高橋 悠真",organization:"北辰ボクシングジム",date:"2026-10-24",venue:"後楽園ホール",division:"ライト級",weight:"61.0kg",rounds:4,klass:"C級",stance:"指定なし",deadline:"2026-09-10",note:"初期キャリアの選手を希望。"}];

export function OpenMatchBoard({databaseConnected,industryMode}:{databaseConnected:boolean;industryMode:boolean}){
  const [items,setItems]=useState<Item[]>(databaseConnected?[]:demo); const [loading,setLoading]=useState(databaseConnected); const [showForm,setShowForm]=useState(false); const [error,setError]=useState("");
  const [division,setDivision]=useState("スーパーバンタム級"); const [date,setDate]=useState(""); const [venue,setVenue]=useState(""); const [weight,setWeight]=useState(""); const [rounds,setRounds]=useState("6"); const [klass,setKlass]=useState("B級"); const [stance,setStance]=useState("指定なし"); const [deadline,setDeadline]=useState(""); const [note,setNote]=useState("");

  useEffect(()=>{
    if(!databaseConnected){return;} if(!industryMode){setLoading(false);return;}
    let active=true;(async()=>{try{const supabase=createClient();const {data,error:loadError}=await supabase.schema("ringops").from("open_matches").select("id,event_date,venue_name,division_code,contract_weight_min_kg,contract_weight_max_kg,rounds,preferred_class,preferred_stance,deadline,comment,target_boxer_id,organization_id").eq("status","open").order("deadline");if(loadError)throw loadError;const boxerIds=[...new Set((data??[]).map((r:any)=>r.target_boxer_id).filter(Boolean))];const orgIds=[...new Set((data??[]).map((r:any)=>r.organization_id).filter(Boolean))];const [{data:boxers},{data:orgs}]=await Promise.all([boxerIds.length?supabase.schema("ringops").from("boxers").select("id,name").in("id",boxerIds):Promise.resolve({data:[]}),orgIds.length?supabase.schema("ringops").from("organizations").select("id,display_name").in("id",orgIds):Promise.resolve({data:[]})]);const boxerMap=new Map((boxers??[]).map((b:any)=>[b.id,b.name]));const orgMap=new Map((orgs??[]).map((o:any)=>[o.id,o.display_name]));const mapped=(data??[]).map((r:any)=>({id:r.id,targetBoxer:boxerMap.get(r.target_boxer_id)??"対戦枠",organization:orgMap.get(r.organization_id)??"業界組織",date:r.event_date??"",venue:r.venue_name??"—",division:codeToDivision[r.division_code]??r.division_code,weight:r.contract_weight_min_kg===r.contract_weight_max_kg?`${r.contract_weight_min_kg}kg`:`${r.contract_weight_min_kg??"—"}〜${r.contract_weight_max_kg??"—"}kg`,rounds:r.rounds,klass:r.preferred_class?`${r.preferred_class}級`:"指定なし",stance:r.preferred_stance==="southpaw"?"左":r.preferred_stance==="orthodox"?"右":"指定なし",deadline:r.deadline??"",note:r.comment??""}));if(active)setItems(mapped);}catch{if(active)setError("募集情報を読み込めませんでした。") }finally{if(active)setLoading(false)}})();return()=>{active=false};
  },[databaseConnected,industryMode]);

  async function create(e:React.FormEvent){e.preventDefault();setError("");if(!databaseConnected){const item:Item={id:`demo-${Date.now()}`,targetBoxer:"対象選手未指定",organization:"自組織",date,venue,division,weight:`${weight}kg`,rounds:Number(rounds),klass,stance,deadline,note};setItems([item,...items]);setShowForm(false);return;}try{const supabase=createClient();const {data:userData}=await supabase.auth.getUser();const user=userData.user;if(!user)throw new Error();const {data:membership}=await supabase.schema("ringops").from("organization_memberships").select("organization_id,role").eq("user_id",user.id).eq("status","active").in("role",["owner","admin","matchmaker"]).limit(1).single();if(!membership)throw new Error();const parsed=Number(weight);const {error:insertError}=await supabase.schema("ringops").from("open_matches").insert({organization_id:membership.organization_id,event_date:date||null,venue_name:venue||null,division_code:divisionCodes[division],contract_weight_min_kg:parsed||null,contract_weight_max_kg:parsed||null,rounds:Number(rounds),preferred_class:classToDb[klass]??null,preferred_stance:stanceToDb[stance]??null,deadline:deadline||null,comment:note||null,status:"open",created_by:user.id});if(insertError)throw insertError;location.reload();}catch{setError("募集を登録できませんでした。組織権限を確認してください。");}}

  if(loading)return <div className="border-y-2 border-slate-950 bg-white py-12 text-center text-sm font-bold text-slate-500">募集情報を読み込んでいます…</div>;
  return <>
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-bold text-slate-500">募集中 {items.length}件</p>{industryMode&&<button className="h-10 bg-slate-950 px-4 text-xs font-black text-white" onClick={()=>setShowForm(!showForm)}>{showForm?"閉じる":"対戦相手募集を作成"}</button>}</div>
    {error&&<div className="mb-4 border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-800">{error}</div>}
    {showForm&&<form className="mb-6 border-y-2 border-slate-950 bg-white p-5" onSubmit={create}><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Select label="階級" value={division} onChange={setDivision} values={divisions}/><Field label="興行日"><input className="input" type="date" required value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="会場"><input className="input" required value={venue} onChange={e=>setVenue(e.target.value)} placeholder="後楽園ホール"/></Field><Field label="契約ウェイト kg"><input className="input" type="number" step="0.01" required value={weight} onChange={e=>setWeight(e.target.value)}/></Field><Select label="R" value={rounds} onChange={setRounds} values={["4","6","8","10","12"]}/><Select label="希望クラス" value={klass} onChange={setKlass} values={["指定なし","A級","B級","C級"]}/><Select label="構え" value={stance} onChange={setStance} values={["指定なし","右","左"]}/><Field label="募集期限"><input className="input" type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/></Field></div><Field label="条件・コメント"><textarea className="mt-1 min-h-24 w-full border border-slate-300 p-3 text-sm" value={note} onChange={e=>setNote(e.target.value)}/></Field><div className="mt-4 text-right"><button className="h-11 bg-slate-950 px-5 text-xs font-black text-white">募集を公開</button></div></form>}
    <div className="border-y-2 border-slate-950 bg-white">{items.map(item=><article className="grid gap-4 border-b border-slate-200 px-5 py-5 last:border-0 lg:grid-cols-[1.45fr_1fr_.8fr_.8fr_1fr] lg:items-center" key={item.id}><div><b>{item.targetBoxer}</b><p className="mt-1 text-xs font-bold text-slate-500">{item.organization}</p><p className="mt-1 text-xs text-slate-400">{item.date}｜{item.venue}</p></div><div><b className="text-sm">{item.division}</b><p className="mt-1 text-xs text-slate-500">{item.weight}</p></div><b>{item.klass} / {item.rounds}R</b><div><p className="text-[11px] text-slate-400">募集期限</p><b>{item.deadline||"未設定"}</b></div><Link className="flex h-10 items-center justify-center border border-slate-950 px-3 text-xs font-black hover:bg-slate-950 hover:text-white" href={`/?division=${encodeURIComponent(item.division)}&class=${encodeURIComponent(item.klass)}&rounds=${item.rounds}`}>この条件で選手を探す</Link>{item.note&&<p className="text-xs leading-5 text-slate-500 lg:col-span-5">{item.note}</p>}</article>)}{!items.length&&<div className="py-12 text-center text-sm font-bold text-slate-500">現在募集中の案件はありません。</div>}</div>
  </>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-[11px] font-black text-slate-500">{label}</span>{children}</label>}
function Select({label,value,onChange,values}:{label:string;value:string;onChange:(v:string)=>void;values:string[]}){return <Field label={label}><select className="input" value={value} onChange={e=>onChange(e.target.value)}>{values.map(v=><option key={v} value={v}>{/^\d+$/.test(v)?`${v}R`:v}</option>)}</select></Field>}
