"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Staff={userId:string;name:string;role:string;status:string};
type Org={id:string;name:string;type:string;role:string};
const roleLabels:Record<string,string>={owner:"オーナー",admin:"管理者",matchmaker:"マッチメーカー",staff:"スタッフ",viewer:"閲覧のみ"};

export function StaffManager({databaseConnected,industryMode}:{databaseConnected:boolean;industryMode:boolean}){
  const [orgs,setOrgs]=useState<Org[]>([]); const [orgId,setOrgId]=useState(""); const [staff,setStaff]=useState<Staff[]>([]); const [loading,setLoading]=useState(databaseConnected); const [error,setError]=useState("");
  const [email,setEmail]=useState(""); const [role,setRole]=useState("staff"); const [inviteUrl,setInviteUrl]=useState(""); const [copied,setCopied]=useState(false);
  const currentOrg=useMemo(()=>orgs.find(o=>o.id===orgId),[orgs,orgId]);

  useEffect(()=>{if(!databaseConnected||!industryMode){setLoading(false);return;}let active=true;(async()=>{try{const supabase=createClient();const {data:userData}=await supabase.auth.getUser();if(!userData.user)throw new Error();const {data:memberships,error:mError}=await supabase.schema("ringops").from("organization_memberships").select("organization_id,role").eq("user_id",userData.user.id).eq("status","active");if(mError)throw mError;const ids=(memberships??[]).map(m=>m.organization_id);const {data:organizationRows,error:oError}=ids.length?await supabase.schema("ringops").from("organizations").select("id,display_name,organization_type").in("id",ids):{data:[],error:null};if(oError)throw oError;const roleMap=new Map((memberships??[]).map(m=>[m.organization_id,m.role]));const mapped=(organizationRows??[]).map((o:any)=>({id:o.id,name:o.display_name,type:o.organization_type,role:roleMap.get(o.id)??"viewer"}));if(active){setOrgs(mapped);setOrgId(mapped[0]?.id??"");}}catch{if(active)setError("所属組織を読み込めませんでした。") }finally{if(active)setLoading(false)}})();return()=>{active=false}},[databaseConnected,industryMode]);

  useEffect(()=>{if(!databaseConnected||!orgId)return;let active=true;(async()=>{try{const supabase=createClient();const {data:memberships,error:mError}=await supabase.schema("ringops").from("organization_memberships").select("user_id,role,status").eq("organization_id",orgId).order("created_at");if(mError)throw mError;const ids=(memberships??[]).map(m=>m.user_id);const {data:profiles}=ids.length?await supabase.schema("ringops").from("profiles").select("id,display_name").in("id",ids):{data:[]};const names=new Map((profiles??[]).map((p:any)=>[p.id,p.display_name]));const mapped=(memberships??[]).map((m:any)=>({userId:m.user_id,name:names.get(m.user_id)??"スタッフ",role:m.role,status:m.status}));if(active)setStaff(mapped);}catch{if(active)setError("スタッフ一覧を読み込めませんでした。")}})();return()=>{active=false}},[databaseConnected,orgId]);

  async function createInvite(e:React.FormEvent){e.preventDefault();setError("");setInviteUrl("");setCopied(false);try{const supabase=createClient();const {data,error:rpcError}=await supabase.schema("ringops").rpc("create_organization_invitation",{p_organization_id:orgId,p_email:email,p_role:role});if(rpcError)throw rpcError;const url=`${window.location.origin}/invite?token=${encodeURIComponent(String(data))}`;setInviteUrl(url);setEmail("");}catch{setError("招待を作成できませんでした。オーナーまたは管理者権限を確認してください。");}}
  async function updateRole(userId:string,nextRole:string){setError("");const previous=staff;setStaff(rows=>rows.map(s=>s.userId===userId?{...s,role:nextRole}:s));try{const supabase=createClient();const {error:updateError}=await supabase.schema("ringops").from("organization_memberships").update({role:nextRole}).eq("organization_id",orgId).eq("user_id",userId);if(updateError)throw updateError;}catch{setStaff(previous);setError("権限を更新できませんでした。オーナー権限を確認してください。");}}
  async function copy(){if(!inviteUrl)return;await navigator.clipboard.writeText(inviteUrl);setCopied(true);}

  if(!databaseConnected)return <div className="border-y-2 border-slate-950 bg-white p-6 text-sm text-slate-500">スタッフ管理はSupabase接続後に有効になります。</div>;
  if(!industryMode)return <div className="border-y-2 border-slate-950 bg-white p-6 text-sm text-slate-500">業界アカウントでログインしてください。</div>;
  if(loading)return <div className="border-y-2 border-slate-950 bg-white p-10 text-center text-sm font-bold text-slate-500">スタッフ情報を読み込んでいます…</div>;

  const canInvite=currentOrg?.role==="owner"||currentOrg?.role==="admin";
  const canChangeRole=currentOrg?.role==="owner";
  return <div className="space-y-6">
    {error&&<div className="border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-800">{error}</div>}
    <section className="border-y-2 border-slate-950 bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] font-black text-slate-400">対象組織</p><select className="mt-1 h-11 min-w-72 border border-slate-300 px-3 text-sm font-black" value={orgId} onChange={e=>setOrgId(e.target.value)}>{orgs.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></div><p className="text-xs text-slate-500">あなたの権限：<b>{roleLabels[currentOrg?.role??""]??currentOrg?.role}</b></p></div></section>
    <section className="border-y-2 border-slate-950 bg-white"><div className="border-b border-slate-200 bg-slate-50 px-5 py-3 text-[11px] font-black text-slate-500">スタッフ・権限</div>{staff.map(s=><div className="grid gap-3 border-b border-slate-200 px-5 py-4 last:border-0 sm:grid-cols-[1fr_180px_120px] sm:items-center" key={s.userId}><div><b>{s.name}</b><p className="mt-1 text-[11px] text-slate-400">{s.status==="active"?"利用中":s.status}</p></div>{canChangeRole&&s.role!=="owner"?<select className="h-10 border border-slate-300 px-2 text-sm font-bold" value={s.role} onChange={e=>updateRole(s.userId,e.target.value)}><option value="admin">管理者</option><option value="matchmaker">マッチメーカー</option><option value="staff">スタッフ</option><option value="viewer">閲覧のみ</option></select>:<span className="text-sm font-black">{roleLabels[s.role]??s.role}</span>}<span className="text-xs text-slate-500">{roleLabels[s.role]??s.role}</span></div>)}{!staff.length&&<div className="p-8 text-center text-sm text-slate-500">スタッフがいません。</div>}</section>
    <section className="border-y-2 border-slate-950 bg-white p-5"><h2 className="text-lg font-black">スタッフを招待</h2><p className="mt-1 text-xs leading-5 text-slate-500">招待リンクは7日間有効です。現段階ではリンクをLINEやメールで本人へ送ります。</p>{canInvite?<form className="mt-5 grid gap-3 sm:grid-cols-[1fr_180px_auto] sm:items-end" onSubmit={createInvite}><Field label="招待するメールアドレス"><input className="input" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="権限"><select className="input" value={role} onChange={e=>setRole(e.target.value)}><option value="admin">管理者</option><option value="matchmaker">マッチメーカー</option><option value="staff">スタッフ</option><option value="viewer">閲覧のみ</option></select></Field><button className="h-11 bg-slate-950 px-5 text-xs font-black text-white">招待リンクを作成</button></form>:<p className="mt-4 text-sm font-bold text-slate-500">招待できるのはオーナーまたは管理者です。</p>}{inviteUrl&&<div className="mt-5 border border-slate-200 bg-slate-50 p-4"><p className="text-[11px] font-black text-slate-400">招待リンク</p><p className="mt-2 break-all text-xs font-bold text-slate-700">{inviteUrl}</p><button className="mt-3 border border-slate-950 px-4 py-2 text-xs font-black" type="button" onClick={copy}>{copied?"コピーしました":"リンクをコピー"}</button></div>}</section>
  </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-[11px] font-black text-slate-500">{label}</span>{children}</label>}
