"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { boxerPreviewData } from "@/features/boxers/data/preview-boxers";

type Row={id:string;name:string;division:string;boxerClass:string;status:"受付中"|"条件次第"|"受付停止";availableFrom:string;minWeight:string;maxWeight:string;rounds:string;travel:string;checked:string;hasStatus:boolean};
const statusToDb={"受付中":"accepting","条件次第":"conditional","受付停止":"paused"} as const;
const dbToStatus={accepting:"受付中",conditional:"条件次第",paused:"受付停止"} as const;
const divisionLabels:Record<string,string>={super_bantam:"スーパーバンタム級",feather:"フェザー級",super_feather:"スーパーフェザー級",light:"ライト級"};

export function StatusManager({databaseConnected,industryMode}:{databaseConnected:boolean;industryMode:boolean}){
  const fallback=boxerPreviewData.slice(0,2).map(b=>({id:b.id,name:b.name,division:b.division,boxerClass:b.boxerClass,status:b.status,availableFrom:b.availableMonth?`${b.availableMonth}-01`:"",minWeight:String(b.minWeight),maxWeight:String(b.maxWeight),rounds:b.rounds.join(","),travel:b.travel,checked:b.verified,hasStatus:true} satisfies Row));
  const [rows,setRows]=useState<Row[]>(databaseConnected?[]:fallback); const [loading,setLoading]=useState(databaseConnected); const [error,setError]=useState(""); const [gymName,setGymName]=useState(databaseConnected?"":"プレビュー用ジム");

  useEffect(()=>{if(!databaseConnected||!industryMode){setLoading(false);return;}let active=true;(async()=>{try{const supabase=createClient();const {data:userData}=await supabase.auth.getUser();if(!userData.user)throw new Error();const {data:memberships}=await supabase.schema("ringops").from("organization_memberships").select("organization_id,role").eq("user_id",userData.user.id).eq("status","active");const ids=(memberships??[]).map(m=>m.organization_id);const {data:orgs}=ids.length?await supabase.schema("ringops").from("organizations").select("id,display_name,organization_type").in("id",ids):{data:[]};const gym=(orgs??[]).find((o:any)=>o.organization_type==="gym");if(!gym){if(active){setGymName("ジム組織未登録");setRows([])}return;}if(active)setGymName(gym.display_name);const {data:boxers,error:boxerError}=await supabase.schema("ringops").from("boxers").select("id,name,division_code,boxer_class").eq("organization_id",gym.id).order("name_kana");if(boxerError)throw boxerError;const boxerIds=(boxers??[]).map((b:any)=>b.id);const {data:statuses}=boxerIds.length?await supabase.schema("ringops").from("boxer_match_statuses").select("boxer_id,status,available_from,min_contract_weight_kg,max_contract_weight_kg,desired_rounds,travel_condition,verified_at").in("boxer_id",boxerIds):{data:[]};const statusMap=new Map((statuses??[]).map((s:any)=>[s.boxer_id,s]));const mapped:Row[]=(boxers??[]).map((b:any)=>{const s:any=statusMap.get(b.id);return{id:b.id,name:b.name,division:divisionLabels[b.division_code]??b.division_code,boxerClass:`${b.boxer_class}級`,status:s?dbToStatus[s.status as keyof typeof dbToStatus]:"受付停止",availableFrom:s?.available_from??"",minWeight:s?.min_contract_weight_kg!=null?String(s.min_contract_weight_kg):"",maxWeight:s?.max_contract_weight_kg!=null?String(s.max_contract_weight_kg):"",rounds:(s?.desired_rounds??[]).join(","),travel:s?.travel_condition??"",checked:s?.verified_at?new Date(s.verified_at).toLocaleString("ja-JP"):"未確認",hasStatus:Boolean(s)}});if(active)setRows(mapped);}catch{if(active)setError("所属選手を読み込めませんでした。") }finally{if(active)setLoading(false)}})();return()=>{active=false}},[databaseConnected,industryMode]);

  function patch(id:string,patch:Partial<Row>){setRows(current=>current.map(row=>row.id===id?{...row,...patch}:row));}
  async function save(row:Row,verifyOnly=false){setError("");if(!databaseConnected){patch(row.id,{checked:"今"});return;}try{const supabase=createClient();const {data:userData}=await supabase.auth.getUser();if(!userData.user)throw new Error();const payload={boxer_id:row.id,status:statusToDb[row.status],available_from:row.availableFrom||null,min_contract_weight_kg:row.minWeight?Number(row.minWeight):null,max_contract_weight_kg:row.maxWeight?Number(row.maxWeight):null,desired_rounds:row.rounds.split(",").map(v=>Number(v.trim())).filter(v=>[4,6,8,10,12].includes(v)),travel_condition:row.travel||null,updated_at:new Date().toISOString(),updated_by:userData.user.id,verified_at:new Date().toISOString(),verified_by:userData.user.id};let saveError;if(row.hasStatus){const result=await supabase.schema("ringops").from("boxer_match_statuses").update(verifyOnly?{verified_at:payload.verified_at,verified_by:payload.verified_by}:payload).eq("boxer_id",row.id);saveError=result.error;}else{const result=await supabase.schema("ringops").from("boxer_match_statuses").insert(payload);saveError=result.error;}if(saveError)throw saveError;patch(row.id,{checked:"今",hasStatus:true});}catch{setError("更新を保存できませんでした。権限と入力値を確認してください。");}}

  if(loading)return <div className="border-y-2 border-slate-950 bg-white py-12 text-center text-sm font-bold text-slate-500">所属選手を読み込んでいます…</div>;
  if(databaseConnected&&!industryMode)return <div className="border-y-2 border-slate-950 bg-white py-12 text-center text-sm font-bold text-slate-500">業界アカウントでログインしてください。</div>;
  return <><div className="mb-3 flex items-center justify-between"><div><p className="text-[11px] font-black text-slate-400">所属ジム</p><h2 className="font-black">{gymName}</h2></div><p className="text-xs text-slate-500">公式戦績はここでは編集しません</p></div>{error&&<div className="mb-4 border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-800">{error}</div>}<div className="border-y-2 border-slate-950 bg-white">{rows.map(r=><article className="border-b border-slate-200 px-5 py-5 last:border-0" key={r.id}><div className="grid gap-3 lg:grid-cols-[1.4fr_150px_160px_110px_110px_130px_1fr_auto] lg:items-end"><div><b>{r.name}</b><p className="mt-1 text-xs text-slate-500">{r.division} / {r.boxerClass}</p></div><Field label="受付状況"><select className="input" value={r.status} onChange={e=>patch(r.id,{status:e.target.value as Row["status"]})}><option>受付中</option><option>条件次第</option><option>受付停止</option></select></Field><Field label="試合可能日"><input className="input" type="date" value={r.availableFrom} onChange={e=>patch(r.id,{availableFrom:e.target.value})}/></Field><Field label="下限kg"><input className="input" inputMode="decimal" value={r.minWeight} onChange={e=>patch(r.id,{minWeight:e.target.value})}/></Field><Field label="上限kg"><input className="input" inputMode="decimal" value={r.maxWeight} onChange={e=>patch(r.id,{maxWeight:e.target.value})}/></Field><Field label="希望R"><input className="input" value={r.rounds} onChange={e=>patch(r.id,{rounds:e.target.value})} placeholder="6,8"/></Field><Field label="遠征"><input className="input" value={r.travel} onChange={e=>patch(r.id,{travel:e.target.value})}/></Field><button className="h-11 bg-slate-950 px-4 text-xs font-black text-white" onClick={()=>save(r)}>保存</button></div><div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-3"><p className="text-[11px] text-slate-500">最終確認：{r.checked}</p><button className="text-xs font-black underline underline-offset-4" onClick={()=>save(r,true)}>内容はそのままで確認日時だけ更新</button></div></article>)}{!rows.length&&<div className="py-12 text-center text-sm font-bold text-slate-500">このジムに所属選手がまだ登録されていません。</div>}</div></>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1 block text-[10px] font-black text-slate-400">{label}</span>{children}</label>}
